#!/bin/bash

# Apply Email Verification Migration - Manual Instructions
# 
# Since the Supabase REST API doesn't support arbitrary SQL execution,
# you'll need to apply the migration manually using one of these methods:

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  EMAIL VERIFICATION MIGRATION - MANUAL APPLICATION REQUIRED   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "The email verification system has been deployed but requires a"
echo "database table to be created in Supabase."
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "METHOD 1: Via Supabase Dashboard (Recommended)"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "1. Open: https://supabase.com/dashboard/project/kstbgnyikroliavpuehi/sql/new"
echo ""
echo "2. Copy the SQL from:"
echo "   supabase/migrations/202604230001_email_verification_tokens.sql"
echo ""
echo "3. Paste it into the SQL editor"
echo ""
echo "4. Click 'Run' (⌘ ↵)"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "METHOD 2: Via Supabase CLI"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "1. Install Supabase CLI:"
echo "   brew install supabase/tap/supabase"
echo ""
echo "2. Link your project:"
echo "   supabase link --project-ref kstbgnyikroliavpuehi"
echo ""
echo "3. Push the migration:"
echo "   supabase db push"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "METHOD 3: Display Full SQL for Copying"
echo "────────────────────────────────────────────────────────────────"
echo ""

# Show the migration file
if [ -f "supabase/migrations/202604230001_email_verification_tokens.sql" ]; then
    echo "Here's the SQL to apply:"
    echo ""
    echo "───────────────────────────────────────────────────────────────"
    cat supabase/migrations/202604230001_email_verification_tokens.sql
    echo ""
    echo "───────────────────────────────────────────────────────────────"
else
    echo "ERROR: Migration file not found!"
    echo "Expected: supabase/migrations/202604230001_email_verification_tokens.sql"
    exit 1
fi

echo ""
echo "────────────────────────────────────────────────────────────────"
echo "VERIFICATION"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "After applying the migration, verify it worked:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/kstbgnyikroliavpuehi/editor"
echo ""
echo "2. Check that 'email_verification_tokens' appears in the"
echo "   list of tables on the left sidebar"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo "TESTING"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "Once the migration is applied, test the flow:"
echo ""
echo "1. Sign up at: http://localhost:3001/acceso/registro"
echo "   or https://cordero-coffee-xxx.vercel.app/acceso/registro"
echo ""
echo "2. Check Resend dashboard for email:"
echo "   https://resend.com/emails"
echo ""
echo "3. Look for an email from 'Cuenta Cordero <cuenta@corderocoffee.mx>'"
echo "   with a verification link"
echo ""
echo "4. Click the link or copy the token to test manually"
echo ""
echo "────────────────────────────────────────────────────────────────"
echo ""
