export const COPY = {
  brand: {
    name: 'Cordero Coffee Club',
    tagline: 'Café de especialidad. Sin esperar.',
    intro: 'Ordena en línea, elige tu horario y sigue tu pedido en tiempo real. Tu café, listo cuando llegas.',
  },
  actions: {
    startOrder: 'Hacer pedido',
    backToHome: 'Volver al inicio',
    accessAccount: 'Entrar o crear cuenta',
    continueAsGuest: 'Continuar como invitado',
    signOut: 'Cerrar sesión',
  },
  auth: {
    title: 'Acceso a Cordero',
    subtitle: 'Inicia sesión o crea una cuenta para guardar tu historial y favoritos.',
    emailLabel: 'Correo electrónico',
    passwordLabel: 'Contraseña',
    loginButton: 'Iniciar sesión',
    registerButton: 'Crear cuenta',
    successRegister: 'Cuenta creada. Revisa tu correo para confirmar el acceso.',
    errorInvalidCredentials: 'No pudimos iniciar sesión con esos datos.',
    errorGeneric: 'Ocurrió un error. Intenta de nuevo.',
    errorMissingFields: 'Completa tu correo y contraseña para continuar.',
  },
  ordering: {
    title: 'Tu pedido',
    cartEmpty: 'Aún no agregas productos.',
    cartTitle: 'Carrito',
    confirmOrder: 'Confirmar pedido',
    confirmingOrder: 'Creando pedido...',
    pickupLabel: 'Retiro',
    paymentLabel: 'Pago',
    notesLabel: 'Notas (opcional)',
    notesPlaceholder: 'Sin azúcar, leche de avena, etc.',
    totalLabel: 'Total estimado',
    historialLink: 'Ver mis pedidos',
    guestMode: 'MODO INVITADO: tu carrito se guarda en este dispositivo.',
  },
  pickup: {
    ahora: 'Ahora',
    agendar: 'Agendar',
    al_llegar: 'Al llegar',
  },
  payment: {
    cash: 'Efectivo',
    card_pending: 'Tarjeta al retirar',
  },
  status: {
    pendiente: 'Pendiente',
    aceptado: 'Aceptado',
    preparando: 'Preparando',
    listo: '¡Listo para recoger!',
    entregado: 'Entregado',
  },
  confirmation: {
    title: '¡Pedido recibido!',
    subtitle: 'Te avisaremos cuando esté listo.',
    trackOrder: 'Seguir mi pedido',
    newOrder: 'Hacer otro pedido',
  },
  historial: {
    title: 'Mis pedidos',
    empty: 'Aún no tienes pedidos. ¡Haz tu primer pedido!',
    reorder: 'Pedir de nuevo',
  },
} as const;
